# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main


pool:
  name: 'ubuntu-latest'
steps:

- task: Bash@3
  inputs:
   script:
     echo "Hello, World"
    
