# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main


pool:
  name: 'Default'
steps:

- task: PowerShell@1
  inputs:
    targetType: 'inline'
    script:
     echo "Hello, World"
    
